./build/JackCompiler "build/JackPrograms/Set 1/Square"
./build/JackCompiler "build/JackPrograms/Set 1/List"
./build/JackCompiler "build/JackPrograms/Set 1/HelloWorld"
./build/JackCompiler "build/JackPrograms/Set 1/Fraction"
./build/JackCompiler "build/JackPrograms/Set 1/Average"

./build/JackCompiler "build/JackPrograms/Set 2/Square"
./build/JackCompiler "build/JackPrograms/Set 2/ExpressionLessSquare"
./build/JackCompiler "build/JackPrograms/Set 2/ArrayTest"

./build/JackCompiler "build/JackPrograms/Set 3/Square"
./build/JackCompiler "build/JackPrograms/Set 3/Seven"
./build/JackCompiler "build/JackPrograms/Set 3/Pong"
./build/JackCompiler "build/JackPrograms/Set 3/ConvertToBin"
./build/JackCompiler "build/JackPrograms/Set 3/ComplexArrays"
./build/JackCompiler "build/JackPrograms/Set 3/Average"

./build/JackCompiler "build/JackPrograms/Set 4/"
./build/JackCompiler "build/JackPrograms/Set 4/SysTest"
./build/JackCompiler "build/JackPrograms/Set 4/StringTest"
./build/JackCompiler "build/JackPrograms/Set 4/ScreenTest"
./build/JackCompiler "build/JackPrograms/Set 4/OutputTest"
./build/JackCompiler "build/JackPrograms/Set 4/MemoryTest"
./build/JackCompiler "build/JackPrograms/Set 4/MathTest"
./build/JackCompiler "build/JackPrograms/Set 4/KeyboardTest"
./build/JackCompiler "build/JackPrograms/Set 4/ArrayTest"